run-ansible:
    name: Run Ansible Playbook
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: listout
        run: |
          pwd
          ls -ltr
          ansible --version
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > key_name.pem
          chmod 400 key_name.pem

      - name: Run Playbook
        run: |
          ansible-playbook -i inventory/dev.ini site.yml